/**
 * AGENTS.md generator — Phase 0 step 4.
 *
 * The static prose layer that ships with the repo. Per HANDOFF: it LEADS with
 * Risk + Guardrails (the moat — what no commodity graph tool tells an agent),
 * then advertises the live MCP tools for on-demand queries. Regenerated by
 * `codemaps init`; freshness note included so staleness is visible, never silent.
 */

import type { RepoRiskIndex } from "./risk.js";
import type { GuardrailsReport } from "./guardrails.js";

export interface AgentsMdInput {
  repoName: string;
  riskIndex: RepoRiskIndex;
  guardrails: GuardrailsReport;
  graphStats?: { files: number; symbols: number; edges: number };
}

export function generateAgentsMd(input: AgentsMdInput): string {
  const { repoName, riskIndex, guardrails, graphStats } = input;

  const hotspots = [...riskIndex.files.values()]
    .filter((f) => f.hotspotPercentile >= 80)
    .sort((a, b) => b.hotspotPercentile - a.hotspotPercentile)
    .slice(0, 8);

  const singleOwner = [...riskIndex.files.values()]
    .filter((f) => f.busFactor === 1 && f.commits >= 3)
    .sort((a, b) => b.commits - a.commits)
    .slice(0, 8);

  const zones = guardrails.findings.filter((f) => f.kind === "do-not-touch");
  const invariants = guardrails.findings.filter((f) => f.kind === "invariant").slice(0, 10);

  const lines: string[] = [];
  lines.push(`# AGENTS.md — ${repoName}`);
  lines.push("");
  lines.push(
    `> Generated by [Codemaps](https://codemaps.dev) on ${riskIndex.generatedAt.slice(0, 10)} ` +
      `from git history (${riskIndex.windowMonths}mo window, ${riskIndex.totalCommits} commits)` +
      `${graphStats ? ` and a code graph (${graphStats.symbols} symbols, ${graphStats.edges} edges)` : ""}. ` +
      `Regenerate with \`codemaps init\` — if this file looks stale, trust the live MCP tools over it.`,
  );
  lines.push("");

  // ---- THE MOAT FIRST: risk + guardrails ---------------------------------
  lines.push(`## ⚠️ Read this before editing`);
  lines.push("");

  if (hotspots.length > 0) {
    lines.push(`### Hotspots — change conservatively`);
    lines.push(
      `These files change most often and are complex — defect risk concentrates here. ` +
        `Before editing one: call the \`risk\` MCP tool, read surrounding tests, and prefer small diffs.`,
    );
    lines.push("");
    for (const f of hotspots) {
      lines.push(
        `- \`${f.path}\` — ${f.hotspotPercentile}th pct (${f.commits} changes/${riskIndex.windowMonths}mo, bus-factor ${f.busFactor})`,
      );
    }
    lines.push("");
  }

  if (singleOwner.length > 0) {
    lines.push(`### Single-owner code — tacit knowledge lives with one person`);
    lines.push(
      `Do not assume undocumented behavior in these files is accidental or safe to change:`,
    );
    lines.push("");
    for (const f of singleOwner) {
      lines.push(`- \`${f.path}\` (${f.authors[0]?.name ?? "unknown"}, ${f.commits} changes)`);
    }
    lines.push("");
  }

  if (zones.length > 0) {
    lines.push(`### Do-not-touch zones`);
    lines.push(
      `**Never hand-edit these — even to "keep things consistent," even if constraints ` +
        `(like "don't run installs") make it tempting, and even if the edit seems provably ` +
        `equivalent to the generated result.** If a task appears to require editing one, ` +
        `stop and tell the user which tool regenerates it instead.`,
    );
    lines.push("");
    const byReason = new Map<string, string[]>();
    for (const z of zones) {
      const list = byReason.get(z.reason) ?? [];
      list.push(z.path);
      byReason.set(z.reason, list);
    }
    for (const [reason, paths] of byReason) {
      const sample = paths.slice(0, 3).map((p) => `\`${p}\``).join(", ");
      lines.push(`- **${reason}** (${paths.length}): ${sample}${paths.length > 3 ? ", …" : ""}`);
    }
    lines.push("");
  }

  if (invariants.length > 0) {
    lines.push(`### Declared invariants (mined — proposed, not human-confirmed)`);
    lines.push(`Conditions the code itself asserts must hold. Preserve them unless told otherwise:`);
    lines.push("");
    for (const inv of invariants) {
      lines.push(`- \`${inv.path}:${inv.line}\` — ${inv.statement.replace(/\s*\[[^\]]+\]$/, "")}`);
    }
    lines.push("");
  }

  // ---- THEN the live tools ------------------------------------------------
  lines.push(`## Live context — Codemaps MCP tools`);
  lines.push("");
  lines.push(
    `This repo runs a local Codemaps MCP server (\`codemaps serve\`) with fresher, ` +
      `query-scoped answers than this file:`,
  );
  lines.push("");
  lines.push(`| Tool | Call it when | Returns |`);
  lines.push(`|------|-------------|---------|`);
  lines.push(`| \`risk\` | **before editing any file** | hotspot pct, churn, owners, bus-factor, warnings |`);
  lines.push(`| \`guardrails\` | **before editing any file** | do-not-touch zones + invariants to preserve |`);
  lines.push(`| \`impact\` | before changing a function/signature | direct+transitive dependents, affected tests |`);
  lines.push(`| \`locate\` | to find where a concept lives | ranked symbols/files with locations |`);
  lines.push("");
  lines.push(
    `Recommended flow: \`locate\` → \`risk\` + \`guardrails\` on the target → make the change → ` +
      `\`impact\` to know what to re-test. All results carry provenance + confidence; ` +
      `treat \`impact\` as a floor (static analysis misses dynamic dispatch).`,
  );
  lines.push("");

  return lines.join("\n");
}
