/**
 * Guardrails lens (thin slice) — "what must stay true / do-not-touch?"
 * (VISION §3 lens 4; DIFFERENTIATION §1)
 *
 * Phase 0 scope: passive mining only.
 *  - Do-not-touch zones: generated / vendored / lockfile / frozen-migration,
 *    detected via path conventions + file-header markers.
 *  - Declared invariants: assertions, validation throws, and "must/never"-style
 *    intent comments already present in the code.
 *
 * Trust loop rules (DIFFERENTIATION §1/§4):
 *  - Everything mined is `proposed` — ADVISORY, never blocking. Only a human
 *    can promote to `confirmed` (Phase 1 capture UX).
 *  - The materiality gate cross-references the Risk lens: proposals anchored to
 *    hotspot / single-owner code are surfaced first; cold-code proposals are
 *    logged but not shouted. This is the concrete lens 4 <-> 5 link.
 */

import { readFile } from "node:fs/promises";
import { listRepoFiles } from "./files.js";
import path from "node:path";
import type { RepoRiskIndex } from "./risk.js";
import { scanSecurity, securityEnrichment, type SecurityCategory } from "./security.js";

// ---------------------------------------------------------------------------
// Model
// ---------------------------------------------------------------------------

export type GuardrailStatus = "proposed" | "confirmed" | "rejected";

export interface GuardrailFinding {
  kind: "do-not-touch" | "invariant";
  /** For do-not-touch: the zone reason. For invariants: "declared". */
  reason:
    | "generated"
    | "vendored"
    | "lockfile"
    | "frozen-migration"
    | "minified"
    | "declared";
  path: string; // repo-relative
  line?: number;
  /** The guardrail statement, human/agent-readable. */
  statement: string;
  status: GuardrailStatus;
  provenance: "mined";
  confidence: number;
  /** Materiality gate result: anchored to hotspot / single-owner code? */
  material: boolean;
  materialWhy?: string;
  /**
   * Security enrichment — the WHY that gives an advisory teeth (born from
   * benchmark failure sendfile-path: an invariant without a consequence loses
   * to a direct user instruction).
   */
  security?: { category: SecurityCategory; consequence: string };
}

export interface GuardrailsReport {
  target: string;
  findings: GuardrailFinding[]; // surfaced, material first
  /** Non-material invariants — logged, not shouted (materiality gate). */
  suppressed: GuardrailFinding[];
}

// ---------------------------------------------------------------------------
// Do-not-touch zone detection
// ---------------------------------------------------------------------------

const ZONE_PATH_RULES: { pattern: RegExp; reason: GuardrailFinding["reason"]; statement: string }[] = [
  { pattern: /(^|\/)(node_modules|vendor|vendored|third_party)\//, reason: "vendored", statement: "Vendored/third-party code — changes will be overwritten or belong upstream." },
  { pattern: /(^|\/)(dist|build|out|\.next)\//, reason: "generated", statement: "Build output — regenerated on every build; edit the source instead." },
  { pattern: /(__generated__|\.generated\.|_generated\.|\.pb\.|_pb2?\.)/, reason: "generated", statement: "Generated code — edit the generator/schema, not this file." },
  { pattern: /(^|\/)(pnpm-lock\.yaml|package-lock\.json|yarn\.lock|Cargo\.lock|poetry\.lock|Gemfile\.lock|composer\.lock|uv\.lock)$/, reason: "lockfile", statement: "Lockfile — managed by the package manager; never hand-edit." },
  { pattern: /(^|\/)migrations?\/.+\.(sql|ts|js|py|rb)$/, reason: "frozen-migration", statement: "Database migration — applied migrations are immutable history; add a new migration instead of editing this one." },
  { pattern: /\.min\.(js|css)$/, reason: "minified", statement: "Minified artifact — edit the source, not this file." },
  { pattern: /(^|\/)\.snap$|\.snap$/, reason: "generated", statement: "Test snapshot — regenerate via the test runner, don't hand-edit." },
];

const HEADER_MARKERS: { pattern: RegExp; statement: string }[] = [
  { pattern: /@generated|code generated by|do not edit|auto-?generated|automatically generated/i, statement: "File header declares it generated / do-not-edit." },
];

// ---------------------------------------------------------------------------
// Declared-invariant mining (regex, language-light; TS/JS-leaning is fine for Phase 0)
// ---------------------------------------------------------------------------

const INVARIANT_PATTERNS: { pattern: RegExp; confidence: number; label: string }[] = [
  // assert(cond, "message") / invariant(cond, "message") / console.assert
  { pattern: /\b(?:assert|invariant)\s*\(([^;]*?),\s*['"`](.+?)['"`]/, confidence: 0.75, label: "assertion" },
  // throw new SomethingError("message") — validation-style guards
  { pattern: /throw\s+new\s+\w*(?:Error|Exception)\w*\s*\(\s*['"`](.+?)['"`]/, confidence: 0.6, label: "validation throw" },
  // Intent comments: // INVARIANT: ... | // MUST ... | // do not ... | // never ...
  { pattern: /\/\/\s*(INVARIANT|IMPORTANT|WARNING|NOTE)?[:\s]*((?:[^\n]*\b(?:must(?:\s+not)?|never|always|do not|don't)\b)[^\n]*)/i, confidence: 0.55, label: "intent comment" },
];

/** Extensions worth mining for invariants (source code, not data/markup). */
const MINEABLE = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".py", ".go", ".rb", ".java", ".rs", ".cs"]);


// ---------------------------------------------------------------------------
// Analysis
// ---------------------------------------------------------------------------

export async function mineGuardrails(
  repoRoot: string,
  target: string,
  riskIndex?: RepoRiskIndex,
): Promise<GuardrailsReport> {
  const rel = normalizeTarget(repoRoot, target);
  // git ls-files based: respects .gitignore (vendored fixtures are not "our code").
  const files = await listRepoFiles(repoRoot, rel);

  // Security surface for the same files — used to enrich invariants with a
  // category + consequence (and to force materiality: security > cold-code).
  const security = await scanSecurity(repoRoot, files);

  const findings: GuardrailFinding[] = [];

  for (const filePath of files) {
    // 1. Path-based zones (no file read needed).
    const zone = ZONE_PATH_RULES.find((r) => r.pattern.test(filePath));
    if (zone) {
      findings.push(finalize({
        kind: "do-not-touch",
        reason: zone.reason,
        path: filePath,
        statement: zone.statement,
        status: "proposed",
        provenance: "mined",
        confidence: 0.85,
        material: false,
      }, riskIndex));
      continue; // don't mine invariants inside generated/vendored code
    }

    // 2. Header markers + invariant mining (single read).
    let source: string;
    try {
      source = await readFile(path.join(repoRoot, filePath), "utf8");
    } catch {
      continue;
    }

    const header = source.split("\n", 10).join("\n");
    const marker = HEADER_MARKERS.find((m) => m.pattern.test(header));
    if (marker) {
      findings.push(finalize({
        kind: "do-not-touch",
        reason: "generated",
        path: filePath,
        line: 1,
        statement: marker.statement,
        status: "proposed",
        provenance: "mined",
        confidence: 0.9,
        material: false,
      }, riskIndex));
      continue;
    }

    const ext = path.extname(filePath);
    if (!MINEABLE.has(ext)) continue;

    const lines = source.split("\n");
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]!;
      for (const rule of INVARIANT_PATTERNS) {
        const m = rule.pattern.exec(line);
        if (!m) continue;
        const statement = (m[2] ?? m[1] ?? "").trim();
        if (statement.length < 8) continue; // too short to be meaningful
        const base: GuardrailFinding = {
          kind: "invariant",
          reason: "declared",
          path: filePath,
          line: i + 1,
          statement: `${statement}${statement.endsWith(".") ? "" : "."} [${rule.label}]`,
          status: "proposed",
          provenance: "mined",
          confidence: rule.confidence,
          material: false,
        };
        // Security enrichment: attach the consequence and force materiality.
        const sec = securityEnrichment(base, security);
        if (sec) {
          base.security = sec;
          base.confidence = Math.max(base.confidence, 0.75);
          base.material = true;
          base.materialWhy = `security-relevant (${sec.category})`;
        }
        findings.push(sec ? base : finalize(base, riskIndex));
        break; // one finding per line
      }
    }
  }

  // Materiality-first ordering; keep do-not-touch zones always visible
  // (they're cheap, high-precision), suppress only non-material invariants.
  const surfaced = findings.filter((f) => f.kind === "do-not-touch" || f.material);
  const suppressed = findings.filter((f) => !(f.kind === "do-not-touch" || f.material));

  surfaced.sort((a, b) => Number(b.material) - Number(a.material) || b.confidence - a.confidence);

  return { target: rel, findings: surfaced, suppressed };
}

/** The materiality gate — the concrete Guardrails <-> Risk link. */
function finalize(f: GuardrailFinding, riskIndex?: RepoRiskIndex): GuardrailFinding {
  if (!riskIndex) return f;
  const risk = riskIndex.files.get(f.path);
  if (!risk) return f;
  if (risk.hotspotPercentile >= 70) {
    return { ...f, material: true, materialWhy: `hotspot (${risk.hotspotPercentile}th pct)` };
  }
  if (risk.busFactor === 1) {
    return { ...f, material: true, materialWhy: `single-owner (bus-factor 1)` };
  }
  return f;
}


function normalizeTarget(repoRoot: string, target: string): string {
  const abs = path.isAbsolute(target) ? target : path.resolve(process.cwd(), target);
  const rel = path.relative(repoRoot, abs);
  return rel.startsWith("..") ? target.replace(/^\.\//, "") : rel.replace(/\\/g, "/") || ".";
}
